### ISSUE TITLE
Cannot save settings

### ISSUE THREAD

**Issue by agross** [vale46n1/immich_duplicate_finder#1]
```
2024-03-21 21:38:48.181 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/Users/agross/Downloads/immich_duplicate_finder/app.py", line 44, in <module>
    immich_server_url, api_key = startup_sidebar()
                                 ^^^^^^^^^^^^^^^^^
  File "/Users/agross/Downloads/immich_duplicate_finder/app.py", line 31, in startup_sidebar
    save_settings_to_db(immich_server_url, api_key, images_folder)
    ^^^^^^^^^^^^^^^^^^^
NameError: name 'save_settings_to_db' is not defined
```

**Comment by vale46n1** [comment]
now should work
