### ISSUE TITLE
list index out of range after running find duplicate photos

### ISSUE THREAD

**Issue by athiosh** [vale46n1/immich_duplicate_finder#26]
Just ran the search for the first time and it returned below error.

`
IndexError: list index out of range
2024-04-19 03:48:09.150 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/immich_duplicate_finder/app.py", line 130, in <module>
    main()
  File "/immich_duplicate_finder/app.py", line 117, in main
    generate_db_duplicate()
  File "/immich_duplicate_finder/imageDuplicate.py", line 187, in generate_db_duplicate
    save_duplicate_pair(metadata[sorted_pair[0]], metadata[sorted_pair[1]], distances[0][j])
                                                  ~~~~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
`

**Comment by vale46n1** [comment]
did you generate the vectore and duplicate db?

**Comment by athiosh** [comment]
Just gave it another try and start vector first and it is working. Thanks
