### ISSUE TITLE
Trying to run via docker but not successful

### ISSUE THREAD

**Issue by Lipown** [vale46n1/immich_duplicate_finder#37]
When starting docker via "docker compose up -d" I see those errors and app will not start:

`immich-duplicate-finder  | 
immich-duplicate-finder  | Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
immich-duplicate-finder  | 
immich-duplicate-finder  | 
immich-duplicate-finder  | Traceback (most recent call last):
immich-duplicate-finder  |   File "/usr/local/bin/streamlit", line 8, in <module>
immich-duplicate-finder  |     sys.exit(main())
immich-duplicate-finder  |              ^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
immich-duplicate-finder  |     return self.main(*args, **kwargs)
immich-duplicate-finder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
immich-duplicate-finder  |     rv = self.invoke(ctx)
immich-duplicate-finder  |          ^^^^^^^^^^^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
immich-duplicate-finder  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
immich-duplicate-finder  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
immich-duplicate-finder  |     return ctx.invoke(self.callback, **ctx.params)
immich-duplicate-finder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
immich-duplicate-finder  |     return __callback(*args, **kwargs)
immich-duplicate-finder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/streamlit/web/cli.py", line 234, in main_run
immich-duplicate-finder  |     _main_run(target, args, flag_options=kwargs)
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/streamlit/web/cli.py", line 270, in _main_run
immich-duplicate-finder  |     bootstrap.run(file, is_hello, args, flag_options)
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/streamlit/web/bootstrap.py", line 386, in run
immich-duplicate-finder  |     _install_pages_watcher(main_script_path)
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/streamlit/web/bootstrap.py", line 362, in _install_pages_watcher
immich-duplicate-finder  |     watch_dir(
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/streamlit/watcher/path_watcher.py", line 151, in watch_dir
immich-duplicate-finder  |     return _watch_path(
immich-duplicate-finder  |            ^^^^^^^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/streamlit/watcher/path_watcher.py", line 126, in _watch_path
immich-duplicate-finder  |     watcher_class(
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/streamlit/watcher/event_based_path_watcher.py", line 95, in __init__
immich-duplicate-finder  |     path_watcher.watch_path(
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/streamlit/watcher/event_based_path_watcher.py", line 173, in watch_path
immich-duplicate-finder  |     folder_handler.watch = self._observer.schedule(
immich-duplicate-finder  |                            ^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/watchdog/observers/api.py", line 323, in schedule
immich-duplicate-finder  |     emitter.start()
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/watchdog/utils/__init__.py", line 92, in start
immich-duplicate-finder  |     self.on_thread_start()
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/watchdog/observers/inotify.py", line 125, in on_thread_start
immich-duplicate-finder  |     self._inotify = InotifyBuffer(path, self.watch.is_recursive, event_mask)
immich-duplicate-finder  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
immich-duplicate-finder  |     self._inotify = Inotify(path, recursive, event_mask)
immich-duplicate-finder  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 174, in __init__
immich-duplicate-finder  |     self._add_dir_watch(path, recursive, event_mask)
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 380, in _add_dir_watch
immich-duplicate-finder  |     self._add_watch(path, mask)
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 401, in _add_watch
immich-duplicate-finder  |     Inotify._raise_error()
immich-duplicate-finder  |   File "/usr/local/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 413, in _raise_error
immich-duplicate-finder  |     raise OSError(errno.ENOSPC, "inotify watch limit reached")
immich-duplicate-finder  | OSError: [Errno 28] inotify watch limit reached
immich-duplicate-finder exited with code 0`

**Comment by Fclem** [comment]
This is not a bug of this software.
Try this on your docker host: https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached and close this Issue

**Comment by saschabrockel** [comment]
@Fclem is right. If you use unRAID use the Tips and Tweaks plugin and increase your `Max user instances` value. The default is 128 and I increased it to 40000 as I have enough left. This is maximum number of inotify instances that a user can create.
