### ISSUE TITLE
[Docker compose] Unable to install

### ISSUE THREAD

**Issue by ZenomeFR** [vale46n1/immich_duplicate_finder#54]
Hi,
I'm trying to install this with Docker compose using the fix from : https://github.com/vale46n1/immich_duplicate_finder/tree/8852d696f6baf3f658279f9d844a430ac13c69ac

I'm getting the following error : `PS G:\immich_duplicate_finder-8852d696f6baf3f658279f9d844a430ac13c69ac\docker> docker compose up -d
[+] Building 101.3s (5/6)                                                                          docker:desktop-linux
 => [immich-duplicate-finder internal] load build definition from Dockerfile                                       0.0s
 => => transferring dockerfile: 363B                                                                               0.0s
 => [immich-duplicate-finder internal] load metadata for docker.io/library/python:latest                           1.1s
 => [immich-duplicate-finder internal] load .dockerignore                                                          0.1s
 => => transferring context: 2B                                                                                    0.0s
 => CACHED [immich-duplicate-finder 1/3] FROM docker.io/library/python:latest@sha256:a31cbb4db18c6f09e3300fa85b77  0.0s
 => ERROR [immich-duplicate-finder 2/3] RUN git clone https://github.com/vale46n1/immich_duplicate_finder.git &&  99.9s
------
 > [immich-duplicate-finder 2/3] RUN git clone https://github.com/vale46n1/immich_duplicate_finder.git && cd immich_duplicate_finder && pip install -r requirements.txt:
0.320 Cloning into 'immich_duplicate_finder'...
2.899 Collecting requests==2.31.0 (from -r requirements.txt (line 1))
3.013   Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
3.128 Collecting streamlit==1.32.2 (from -r requirements.txt (line 2))
3.144   Downloading streamlit-1.32.2-py2.py3-none-any.whl.metadata (8.5 kB)
3.192 Collecting streamlit-image-comparison==0.0.4 (from -r requirements.txt (line 3))
3.210   Downloading streamlit_image_comparison-0.0.4-py3-none-any.whl.metadata (4.2 kB)
3.442 Collecting numpy==1.26.4 (from -r requirements.txt (line 4))
3.458   Downloading numpy-1.26.4.tar.gz (15.8 MB)
4.084      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 26.8 MB/s eta 0:00:00
6.574   Installing build dependencies: started
11.36   Installing build dependencies: finished with status 'done'
11.36   Getting requirements to build wheel: started
11.70   Getting requirements to build wheel: finished with status 'done'
11.71   Installing backend dependencies: started
12.60   Installing backend dependencies: finished with status 'done'
12.60   Preparing metadata (pyproject.toml): started
72.60   Preparing metadata (pyproject.toml): still running...
94.36   Preparing metadata (pyproject.toml): finished with status 'done'
94.66 Collecting pillow==10.2.0 (from -r requirements.txt (line 5))
94.68   Downloading pillow-10.2.0.tar.gz (46.2 MB)
95.99      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 35.3 MB/s eta 0:00:00
96.87   Installing build dependencies: started
98.84   Installing build dependencies: finished with status 'done'
98.84   Getting requirements to build wheel: started
98.99   Getting requirements to build wheel: finished with status 'error'
98.99   error: subprocess-exited-with-error
98.99
98.99   × Getting requirements to build wheel did not run successfully.
98.99   │ exit code: 1
98.99   ╰─> [21 lines of output]
98.99       Traceback (most recent call last):
98.99         File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
98.99           main()
98.99           ~~~~^^
98.99         File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
98.99           json_out['return_val'] = hook(**hook_input['kwargs'])
98.99                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
98.99         File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
98.99           return hook(config_settings)
98.99         File "/tmp/pip-build-env-eseq93s6/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
98.99           return self._get_build_requires(config_settings, requirements=[])
98.99                  ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
98.99         File "/tmp/pip-build-env-eseq93s6/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
98.99           self.run_setup()
98.99           ~~~~~~~~~~~~~~^^
98.99         File "/tmp/pip-build-env-eseq93s6/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
98.99           exec(code, locals())
98.99           ~~~~^^^^^^^^^^^^^^^^
98.99         File "<string>", line 31, in <module>
98.99         File "<string>", line 28, in get_version
98.99       KeyError: '__version__'
98.99       [end of output]
98.99
98.99   note: This error originates from a subprocess, and is likely not a problem with pip.
99.16 error: subprocess-exited-with-error
99.16
99.16 × Getting requirements to build wheel did not run successfully.
99.16 │ exit code: 1
99.16 ╰─> See above for output.
99.16
99.16 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: process "/bin/sh -c git clone https://github.com/vale46n1/immich_duplicate_finder.git && cd immich_duplicate_finder && pip install -r requirements.txt" did not complete successfully: exit code: 1
PS G:\immich_duplicate_finder-8852d696f6baf3f658279f9d844a430ac13c69ac\docker>`

Thanks for your support and for this software :)
Regards

**Comment by bruvv** [comment]
please use the normal docker files here: https://github.com/vale46n1/immich_duplicate_finder/tree/main/docker they work, unfortunately the app itself doesn't work so it is still useless :P
